version: '3'
services:
  nginx:
    image: nginx:${NGINX_VERSION:-1.19.6-alpine}
    restart: unless-stopped
    #network_mode: host
    ports:
      - "${NGINX_HTTP_PORT:-80}:${NGINX_HTTP_PORT:-80}"
      - "${NGINX_HTTPS_PORT:-443}:${NGINX_HTTPS_PORT:-443}"
    depends_on:
      - homeserver
    volumes:
      - ./www:/usr/share/nginx/html:ro
      - ./certificate:/etc/certificate:ro
      - ./templates:/etc/nginx/templates:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
      - HTTP_PORT=${NGINX_HTTP_PORT:-80}
      - HTTPS_PORT=${NGINX_HTTPS_PORT:-443}
      - HOMESERVER_URL=${HOMESERVER_URL:-http://homeserver:8008}

  homeserver:
    image: matrixdotorg/synapse:${HOMESERVER_VERSION:-v1.24.0}
    restart: unless-stopped
    #ports:
    #  - 8008:8008
    #working_dir: /var/www/html
    volumes:
      - ./data/synapse:/data
      - ./data/synapse.yaml:/data/homeserver.yaml
    environment:
      TZ: Asia/Shanghai
      SYNAPSE_DATA_DIR: /data
      SYNAPSE_CONFIG_DIR: /data
      SYNAPSE_REPORT_STATS: "no"
      SYNAPSE_SERVER_NAME: chat.aibaby.online
